### ISSUE TITLE
Support aarch64

### ISSUE THREAD

**Issue by coreybruce** [pmret/papermario#1125] opened 2023-11-12 08:23 UTC
Hey I just wanted to report a issue when I tried to do ```./configure``` on Manjaro Arm64

```
./configure            
configure: looking for baserom ver/us/baserom.z64...found
configure: looking for baserom ver/jp/baserom.z64...missing
configure: looking for baserom ver/ique/baserom.z64...missing
configure: looking for baserom ver/pal/baserom.z64...missing
configure: configuring version us
Traceback (most recent call last):
  File "/home/corey/projects/papermario/tools/build/configure.py", line 1413, in <module>
    configure.split(not args.no_split_assets, args.split_code, args.shift, args.debug)
  File "/home/corey/projects/papermario/tools/build/configure.py", line 381, in split
    import split
  File "/home/corey/projects/papermario/tools/splat/split.py", line 9, in <module>
    from disassembler import disassembler_instance
  File "/home/corey/projects/papermario/tools/splat/disassembler/__init__.py", line 2, in <module>
    from .spimdisasm_disassembler import SpimdisasmDisassembler
  File "/home/corey/projects/papermario/tools/splat/disassembler/spimdisasm_disassembler.py", line 2, in <module>
    import spimdisasm
ModuleNotFoundError: No module named 'spimdisasm'
```

**Comment by ethteck** [comment] 2023-11-12 08:29
Hi! It looks like you may not have installed the project dependencies. I think if you start from here, you should be all set: https://github.com/pmret/papermario/blob/main/SETUP.md#unix

**Comment by coreybruce** [comment] 2023-11-12 08:46
> Hi! It looks like you may not have installed the project dependencies. I think if you start from here, you should be all set: https://github.com/pmret/papermario/blob/main/SETUP.md#unix

Hmm ok well I installed curl git python python-pip python-setuptools base-devel zlib libyaml ninja and binutils and I installed pigment64 via cargo but oh I see there is a python part, I ran  python3 -m pip install -U -r requirements.txt and ran into this issue

```
python3 -m pip install -U -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

I would recommend listing out all the dependencies for the distro in the build documentation as another option as a script can cause issues and also doesn't recognize Manjaro or Manjaro Arm64

**Comment by Alto1772** [comment] 2023-11-12 08:47
Arch Linux (& its deriatives) now prohibits installing Python packages in the system directory (/usr/lib/python3.x). The recommended approach will be to create a python virtual environment then installing those packages within inside of it.

```bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
...
```
However, this method doesn't persist between shell instances, so you gonna have to do `source venv/bin/activate` over a new shell instance.

If you want to still force them to be installed on the system:
```bash
sudo pip install --break-system-packages -r requirements.txt
```

**Comment by coreybruce** [comment] 2023-11-12 08:51
> Arch Linux (& its deriatives) now prohibits installing Python packages in the system directory (/usr/lib/python3.x). The recommended approach will be to create a python virtual environment then installing those packages within inside of it.
> 
> ```shell
> python -m venv venv
> source venv/bin/activate
> pip install -r requirements.txt
> ...
> ```
> 
> However, this method doesn't persist between shell instances, so you gonna have to do `source venv/bin/activate` over a new shell instance.
> 
> If you want to still force them to be installed on the system:
> 
> ```shell
> sudo pip install --break-system-packages -r requirements.txt
> ```

Ah I see I believe a of the python packages are also on the Arch/derivative repos also but you would have to look into which ones are etc

I'll take the safe recommended approach with the first option

**Comment by ethteck** [comment] 2023-11-12 08:53
We're in a transition period where we plan to write a general-purpose setup readme rather than have a script. We've found that a script is hard to maintain. We want to encourage the community to keep documentation up-to-date and explain what the commands involved are, rather than just asking the users to sudo run some mysterious script (which would install system packages) like we used to.

If you're interested in helping with said readme, happy to work with you on it. But anyway, let us know if you have any other issues setting up the project. Shall I close this issue for now?

**Comment by coreybruce** [comment] 2023-11-12 12:09
Sorry for the late reply. Ahh yeah I see and that's understandable, I am always happy to help projects out and you have been quick and very helpful on the issue post if the one condition is I get credited  :smile: 

I ran into this running ninja

```
papermario]$ ninja
[4/10965] as ver/us/asm/header.s
FAILED: ver/us/build/ver/us/asm/header.s.o 
cpp -w -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc   ver/us/asm/header.s -o  - | mips-linux-gnu-as -EB -march=vr4300 -mtune=vr4300 -Iinclude -o ver/us/build/ver/us/asm/header.s.o
/bin/sh: line 1: mips-linux-gnu-as: command not found
[9/10965] /home/corey/projects/paperma...scripts.yaml src/item_hud_scripts.yaml
ninja: build stopped: subcommand failed.
```

I assume I need mips-linux-gnu-binutils installed also? tho I had to add aarch64 to the makepkg build file so it  into this next 

```
[1/10951] cc_272 src/os/pimgr.c
FAILED: ver/us/build/src/os/pimgr.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/pimgr.c -o ver/us/build/src/os/pimgr.c.o && mips-linux-gnu-objcopy -N src/os/pimgr.c ver/us/build/src/os/pimgr.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: No such file or directory
[2/10951] cc_272 src/os/epiwrite.c
FAILED: ver/us/build/src/os/epiwrite.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epiwrite.c -o ver/us/build/src/os/epiwrite.c.o && mips-linux-gnu-objcopy -N src/os/epiwrite.c ver/us/build/src/os/epiwrite.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: No such file or directory
[3/10951] cc_272 src/os/epiread.c
FAILED: ver/us/build/src/os/epiread.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epiread.c -o ver/us/build/src/os/epiread.c.o && mips-linux-gnu-objcopy -N src/os/epiread.c ver/us/build/src/os/epiread.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: No such file or directory
[4/10951] cc_272 src/os/epirawdma.c
FAILED: ver/us/build/src/os/epirawdma.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epirawdma.c -o ver/us/build/src/os/epirawdma.c.o && mips-linux-gnu-objcopy -N src/os/epirawdma.c ver/us/build/src/os/epirawdma.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: No such file or directory
[5/10951] cc_272 src/os/epidma.c
FAILED: ver/us/build/src/os/epidma.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epidma.c -o ver/us/build/src/os/epidma.c.o && mips-linux-gnu-objcopy -N src/os/epidma.c ver/us/build/src/os/epidma.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: No such file or directory
[6/10951] cc_272 src/os/epilinkhandle.c
FAILED: ver/us/build/src/os/epilinkhandle.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epilinkhandle.c -o ver/us/build/src/os/epilinkhandle.c.o && mips-linux-gnu-objcopy -N src/os/epilinkhandle.c ver/us/build/src/os/epilinkhandle.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: No such file or directory
ninja: build stopped: subcommand failed.
```

Not quite done with this issue yet I'm afraid

**Comment by ethteck** [comment] 2023-11-12 12:14
Everyone who contributes is implicitly credited by virtue of having their commits in the repo's history. we don't have a credits list or anything though if that's what you meant. no pressure though, just was an offer in case you're interested.

Yeah, the script being out of date is a known issue, which is why we want to move to a more readme-based solution as mentioned above.

The double forward slash is a bit concerning there, but maybe not a big deal. What do you have in `tools/build/cc/gcc2.7.2` ?

**Comment by coreybruce** [comment] 2023-11-12 12:22
> Everyone who contributes is implicitly credited by virtue of having their commits in the repo's history. we don't have a credits list or anything though if that's what you meant. no pressure though, just was an offer in case you're interested.
> 
> Yeah, the script being out of date is a known issue, which is why we want to move to a more readme-based solution as mentioned above.
> 
> The double forward slash is a bit concerning there, but maybe not a big deal. What do you have in `tools/build/cc/gcc2.7.2` ?

I'm ok with that

Uh there is nothing in that directory

**Comment by ethteck** [comment] 2023-11-12 12:25
This compiler is downloaded when you run `./install_compilers.sh`. Did you maybe miss this step, or is the script not doing anything?

**Comment by coreybruce** [comment] 2023-11-12 12:31
Ohh I see well I didn't bother trying the scripts as the first one for deps didn't work but I just run it and it didn't have any problems luckily tho I would rely on repo packages instead as it seems it downloaded the binaries for the wrong architecture 

```
ninja
[1/10951] cc_272 src/os/pimgr.c
FAILED: ver/us/build/src/os/pimgr.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/pimgr.c -o ver/us/build/src/os/pimgr.c.o && mips-linux-gnu-objcopy -N src/os/pimgr.c ver/us/build/src/os/pimgr.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: cannot execute binary file: Exec format error
[2/10951] cc_272 src/os/epiwrite.c
FAILED: ver/us/build/src/os/epiwrite.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epiwrite.c -o ver/us/build/src/os/epiwrite.c.o && mips-linux-gnu-objcopy -N src/os/epiwrite.c ver/us/build/src/os/epiwrite.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: cannot execute binary file: Exec format error
[3/10951] cc_272 src/os/epiread.c
FAILED: ver/us/build/src/os/epiread.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epiread.c -o ver/us/build/src/os/epiread.c.o && mips-linux-gnu-objcopy -N src/os/epiread.c ver/us/build/src/os/epiread.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: cannot execute binary file: Exec format error
[4/10951] cc_272 src/os/epirawdma.c
FAILED: ver/us/build/src/os/epirawdma.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epirawdma.c -o ver/us/build/src/os/epirawdma.c.o && mips-linux-gnu-objcopy -N src/os/epirawdma.c ver/us/build/src/os/epirawdma.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: cannot execute binary file: Exec format error
[5/10951] cc_272 src/os/epidma.c
FAILED: ver/us/build/src/os/epidma.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epidma.c -o ver/us/build/src/os/epidma.c.o && mips-linux-gnu-objcopy -N src/os/epidma.c ver/us/build/src/os/epidma.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: cannot execute binary file: Exec format error
[6/10951] cc_272 src/os/epilinkhandle.c
FAILED: ver/us/build/src/os/epilinkhandle.c.o 
bash -o pipefail -c 'COMPILER_PATH=tools/build/cc/gcc2.7.2/ tools/build/cc/gcc2.7.2//gcc -Iver/us/include -Iver/us/build/include -Iinclude -Isrc -Iassets/us -D_LANGUAGE_C -D_FINALROM -DVERSION=us -DF3DEX_GBI_2 -D_MIPS_SZLONG=32 -nostdinc  -DVERSION_US -c -G0 -mgp32 -mfp32 -mips3  -Wmissing-braces -Wimplicit -Wredundant-decls -Wstrict-prototypes -Wno-redundant-decls -O3 src/os/epilinkhandle.c -o ver/us/build/src/os/epilinkhandle.c.o && mips-linux-gnu-objcopy -N src/os/epilinkhandle.c ver/us/build/src/os/epilinkhandle.c.o'
bash: line 1: tools/build/cc/gcc2.7.2//gcc: cannot execute binary file: Exec format error
ninja: build stopped: subcommand failed.
```

**Comment by ethteck** [comment] 2023-11-12 12:37
Wait, sorry I might have misunderstood. You're running arch on arm? I don't think the repo supports that. We don't have arm versions of the compilers. If you're on an mac, rosetta lets you still run the compilers, but if you're on linux, I don't think this is going to work.

**Comment by coreybruce** [comment] 2023-11-12 12:47
> Wait, sorry I might have misunderstood. You're running arch on arm? I don't think the repo supports that. We don't have arm versions of the compilers. If you're on an mac, rosetta lets you still run the compilers, but if you're on linux, I don't think this is going to work.

Right that is why I was saying you should rely on the packages on the repo because I have gcc 12.1.0 installed on my system for Arm so it can but the current way is a very hacky workaround

**Comment by ethteck** [comment] 2023-11-12 12:49
gcc 12.1.0 isn't going to produce a matching build of the rom, so it's a non-starter (unless you're not looking to match). you need our exact compiler versions to produce a matching build

**Comment by nanaian** [comment] 2023-11-14 03:54
Duplicate of https://github.com/pmret/gcc-papermario/issues/12

**Closed by nanaian** 2023-11-14 03:54 UTC
