### ISSUE TITLE
Move assets unchanged between versions to assets/core/ directory

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#1002] opened 2023-03-26 16:41 UTC
The version-specific asset directories should be overrides, not full dumps.
Presumably, lots of files won't have changed between versions.

There's a number of sub-tasks here:

1. Figure out which assets are different between versions (for now, we could just compare us and pal?) - need a script for this
2. Somehow tell splat the output folder for each asset, or move assets post-split
3. Add `core` to the asset stack of all versions

**Comment by ethteck** [comment] 2023-06-04 13:13
Duplicate of #392

**Closed by ethteck** 2023-06-04 13:13 UTC
